# -*- coding: utf-8 -*-
# Generated by Django 1.10b1 on 2017-01-14 14:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='test',
            fields=[
                ('test2', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
            ],
        ),
    ]
